//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OctofyExp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OctofyExp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octofy Express.
        /// </summary>
        internal static string A000 {
            get {
                return ResourceManager.GetString("A000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Blanks).
        /// </summary>
        internal static string A001 {
            get {
                return ResourceManager.GetString("A001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick analysis on top {0} rows.
        /// </summary>
        internal static string A002 {
            get {
                return ResourceManager.GetString("A002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to {0}....
        /// </summary>
        internal static string A003 {
            get {
                return ResourceManager.GetString("A003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to the data source..
        /// </summary>
        internal static string A004 {
            get {
                return ResourceManager.GetString("A004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failure.
        /// </summary>
        internal static string A005 {
            get {
                return ResourceManager.GetString("A005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no column in the table that can be used for analysis..
        /// </summary>
        internal static string A006 {
            get {
                return ResourceManager.GetString("A006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No categorical column.
        /// </summary>
        internal static string A007 {
            get {
                return ResourceManager.GetString("A007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.
        /// </summary>
        internal static string A008 {
            get {
                return ResourceManager.GetString("A008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available.
        /// </summary>
        internal static string A009 {
            get {
                return ResourceManager.GetString("A009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while calculating {0}%....
        /// </summary>
        internal static string A010 {
            get {
                return ResourceManager.GetString("A010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading data....
        /// </summary>
        internal static string A011 {
            get {
                return ResourceManager.GetString("A011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while loading data. It may take a while...
        /// </summary>
        internal static string A012 {
            get {
                return ResourceManager.GetString("A012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load the data.
        /// </summary>
        internal static string A013 {
            get {
                return ResourceManager.GetString("A013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following column(s) in {0} have been excluded:.
        /// </summary>
        internal static string A014 {
            get {
                return ResourceManager.GetString("A014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded columns.
        /// </summary>
        internal static string A015 {
            get {
                return ResourceManager.GetString("A015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load data: {0}s.
        /// </summary>
        internal static string A016 {
            get {
                return ResourceManager.GetString("A016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} rows.
        /// </summary>
        internal static string A017 {
            get {
                return ResourceManager.GetString("A017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table analysis....
        /// </summary>
        internal static string A018 {
            get {
                return ResourceManager.GetString("A018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while performing data analysis....
        /// </summary>
        internal static string A019 {
            get {
                return ResourceManager.GetString("A019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table analysis: {0}s.
        /// </summary>
        internal static string A020 {
            get {
                return ResourceManager.GetString("A020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build data for the chart....
        /// </summary>
        internal static string A021 {
            get {
                return ResourceManager.GetString("A021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build chart data: {0}s.
        /// </summary>
        internal static string A022 {
            get {
                return ResourceManager.GetString("A022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 blank excluded.
        /// </summary>
        internal static string A023 {
            get {
                return ResourceManager.GetString("A023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} blanks excluded.
        /// </summary>
        internal static string A024 {
            get {
                return ResourceManager.GetString("A024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories: {0}.
        /// </summary>
        internal static string A025 {
            get {
                return ResourceManager.GetString("A025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Subtotal).
        /// </summary>
        internal static string A026 {
            get {
                return ResourceManager.GetString("A026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string A027 {
            get {
                return ResourceManager.GetString("A027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent.
        /// </summary>
        internal static string A028 {
            get {
                return ResourceManager.GetString("A028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while calculating....
        /// </summary>
        internal static string A029 {
            get {
                return ResourceManager.GetString("A029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude blanks of Y-axis.
        /// </summary>
        internal static string A030 {
            get {
                return ResourceManager.GetString("A030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include blanks of Y-axis.
        /// </summary>
        internal static string A031 {
            get {
                return ResourceManager.GetString("A031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No match found!.
        /// </summary>
        internal static string A032 {
            get {
                return ResourceManager.GetString("A032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are too many categories in this table column..
        /// </summary>
        internal static string A033 {
            get {
                return ResourceManager.GetString("A033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category names are too long..
        /// </summary>
        internal static string A034 {
            get {
                return ResourceManager.GetString("A034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data type of the column is not supported..
        /// </summary>
        internal static string A035 {
            get {
                return ResourceManager.GetString("A035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database connection does not specified..
        /// </summary>
        internal static string A036 {
            get {
                return ResourceManager.GetString("A036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude blanks.
        /// </summary>
        internal static string A037 {
            get {
                return ResourceManager.GetString("A037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include blanks.
        /// </summary>
        internal static string A038 {
            get {
                return ResourceManager.GetString("A038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating....
        /// </summary>
        internal static string A039 {
            get {
                return ResourceManager.GetString("A039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Populating the chart....
        /// </summary>
        internal static string A040 {
            get {
                return ResourceManager.GetString("A040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        internal static string A041 {
            get {
                return ResourceManager.GetString("A041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Data - {0}.
        /// </summary>
        internal static string A042 {
            get {
                return ResourceManager.GetString("A042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows: {0}.
        /// </summary>
        internal static string A043 {
            get {
                return ResourceManager.GetString("A043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following column(s) in {0} have been excluded:.
        /// </summary>
        internal static string A044 {
            get {
                return ResourceManager.GetString("A044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No table or view specified..
        /// </summary>
        internal static string A045 {
            get {
                return ResourceManager.GetString("A045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Object to view.
        /// </summary>
        internal static string A046 {
            get {
                return ResourceManager.GetString("A046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y-axis column:.
        /// </summary>
        internal static string A047 {
            get {
                return ResourceManager.GetString("A047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement column:.
        /// </summary>
        internal static string A048 {
            get {
                return ResourceManager.GetString("A048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of categories exceed the maximum setting.
        /// </summary>
        internal static string A049 {
            get {
                return ResourceManager.GetString("A049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category text length exceed the maximum setting.
        /// </summary>
        internal static string A050 {
            get {
                return ResourceManager.GetString("A050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-categorical column.
        /// </summary>
        internal static string A051 {
            get {
                return ResourceManager.GetString("A051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date time column.
        /// </summary>
        internal static string A052 {
            get {
                return ResourceManager.GetString("A052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty column.
        /// </summary>
        internal static string A053 {
            get {
                return ResourceManager.GetString("A053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system cannot calculate the frequencies on a binary column..
        /// </summary>
        internal static string A054 {
            get {
                return ResourceManager.GetString("A054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data type not support.
        /// </summary>
        internal static string A055 {
            get {
                return ResourceManager.GetString("A055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system cannot calculate the frequencies on a text column..
        /// </summary>
        internal static string A056 {
            get {
                return ResourceManager.GetString("A056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string A057 {
            get {
                return ResourceManager.GetString("A057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete {0}?.
        /// </summary>
        internal static string A058 {
            get {
                return ResourceManager.GetString("A058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Connection Item.
        /// </summary>
        internal static string A059 {
            get {
                return ResourceManager.GetString("A059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete the fields above..
        /// </summary>
        internal static string A060 {
            get {
                return ResourceManager.GetString("A060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields not complete.
        /// </summary>
        internal static string A061 {
            get {
                return ResourceManager.GetString("A061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script has been copied to the clipboard..
        /// </summary>
        internal static string A062 {
            get {
                return ResourceManager.GetString("A062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Starts with).
        /// </summary>
        internal static string A063 {
            get {
                return ResourceManager.GetString("A063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Ends with).
        /// </summary>
        internal static string A064 {
            get {
                return ResourceManager.GetString("A064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Equals).
        /// </summary>
        internal static string A065 {
            get {
                return ResourceManager.GetString("A065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Contains).
        /// </summary>
        internal static string A067 {
            get {
                return ResourceManager.GetString("A067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No match found.
        /// </summary>
        internal static string A068 {
            get {
                return ResourceManager.GetString("A068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One item found.
        /// </summary>
        internal static string A069 {
            get {
                return ResourceManager.GetString("A069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items found.
        /// </summary>
        internal static string A070 {
            get {
                return ResourceManager.GetString("A070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter numeric only..
        /// </summary>
        internal static string A071 {
            get {
                return ResourceManager.GetString("A071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input.
        /// </summary>
        internal static string A072 {
            get {
                return ResourceManager.GetString("A072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a number between 256 and {0}..
        /// </summary>
        internal static string A073 {
            get {
                return ResourceManager.GetString("A073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a number between 16 and 128..
        /// </summary>
        internal static string A074 {
            get {
                return ResourceManager.GetString("A074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a number between 100 and 999999..
        /// </summary>
        internal static string A075 {
            get {
                return ResourceManager.GetString("A075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} by {1}.
        /// </summary>
        internal static string A076 {
            get {
                return ResourceManager.GetString("A076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system cannot calculate the frequencies for this column..
        /// </summary>
        internal static string A077 {
            get {
                return ResourceManager.GetString("A077", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succeed!.
        /// </summary>
        internal static string A078 {
            get {
                return ResourceManager.GetString("A078", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection testing.
        /// </summary>
        internal static string A079 {
            get {
                return ResourceManager.GetString("A079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to the database!.
        /// </summary>
        internal static string A080 {
            get {
                return ResourceManager.GetString("A080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter database connection string..
        /// </summary>
        internal static string A081 {
            get {
                return ResourceManager.GetString("A081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap area_percentage_icon {
            get {
                object obj = ResourceManager.GetObject("area_percentage_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BarChartIcon {
            get {
                object obj = ResourceManager.GetObject("BarChartIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cancel_icon_16 {
            get {
                object obj = ResourceManager.GetObject("cancel_icon_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap checkmark {
            get {
                object obj = ResourceManager.GetObject("checkmark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clear_all_16 {
            get {
                object obj = ResourceManager.GetObject("clear_all_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap copy_chart {
            get {
                object obj = ResourceManager.GetObject("copy_chart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap copy_selections {
            get {
                object obj = ResourceManager.GetObject("copy_selections", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap data_grid {
            get {
                object obj = ResourceManager.GetObject("data_grid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete_icon {
            get {
                object obj = ResourceManager.GetObject("delete_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap down_arrow {
            get {
                object obj = ResourceManager.GetObject("down_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap down_arrow1 {
            get {
                object obj = ResourceManager.GetObject("down_arrow1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Excla_mark {
            get {
                object obj = ResourceManager.GetObject("Excla_mark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_exit {
            get {
                object obj = ResourceManager.GetObject("icon_exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap include_blanks {
            get {
                object obj = ResourceManager.GetObject("include_blanks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap no_blanks {
            get {
                object obj = ResourceManager.GetObject("no_blanks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pie_chart {
            get {
                object obj = ResourceManager.GetObject("pie_chart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search_icon {
            get {
                object obj = ResourceManager.GetObject("search_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap select_all_16 {
            get {
                object obj = ResourceManager.GetObject("select_all_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SimplBarChart {
            get {
                object obj = ResourceManager.GetObject("SimplBarChart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sort_icon_16 {
            get {
                object obj = ResourceManager.GetObject("sort_icon_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stacked_column {
            get {
                object obj = ResourceManager.GetObject("stacked_column", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap to_excel {
            get {
                object obj = ResourceManager.GetObject("to_excel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ToPPT16 {
            get {
                object obj = ResourceManager.GetObject("ToPPT16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap up_arrow {
            get {
                object obj = ResourceManager.GetObject("up_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
