//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OctofyLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OctofyLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are too many data points to fit into the chart..
        /// </summary>
        internal static string B001 {
            get {
                return ResourceManager.GetString("B001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are too many data series to display..
        /// </summary>
        internal static string B002 {
            get {
                return ResourceManager.GetString("B002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Blanks).
        /// </summary>
        internal static string B003 {
            get {
                return ResourceManager.GetString("B003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count:  {0}.
        /// </summary>
        internal static string B004 {
            get {
                return ResourceManager.GetString("B004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand total:  {0}.
        /// </summary>
        internal static string B005 {
            get {
                return ResourceManager.GetString("B005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of legend item.
        /// </summary>
        internal static string B006 {
            get {
                return ResourceManager.GetString("B006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of legend items is 1 to 256..
        /// </summary>
        internal static string B007 {
            get {
                return ResourceManager.GetString("B007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1} to {2}.
        /// </summary>
        internal static string B008 {
            get {
                return ResourceManager.GetString("B008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are too many data series or data points to fit in this chart..
        /// </summary>
        internal static string B009 {
            get {
                return ResourceManager.GetString("B009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand total of {0}:  {1}.
        /// </summary>
        internal static string B010 {
            get {
                return ResourceManager.GetString("B010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} by {1}.
        /// </summary>
        internal static string B011 {
            get {
                return ResourceManager.GetString("B011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} to {1}.
        /// </summary>
        internal static string B012 {
            get {
                return ResourceManager.GetString("B012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select reporting date range..
        /// </summary>
        internal static string B013 {
            get {
                return ResourceManager.GetString("B013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} items in this category. Do you want to load them?.
        /// </summary>
        internal static string B014 {
            get {
                return ResourceManager.GetString("B014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning of slow operation.
        /// </summary>
        internal static string B015 {
            get {
                return ResourceManager.GetString("B015", resourceCulture);
            }
        }
    }
}
